version: "2"
services:
  nacos:
    image: 192.168.3.201:80/library/nacos/nacos-server:v2.0.3
    container_name: nacos-standalone-mysql
    env_file:
      - ./conf/env/nacos-standlone-mysql.env
    volumes:
      - /mnt/nacos/logs:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    extra_hosts:
      - "nacos-mysql.in.gen10.mly0110.org.cn:192.168.3.203"
    restart: on-failure
  mysql:
    container_name: mysql
    image: 192.168.3.201:80/library/nacos/nacos-mysql:5.7
    env_file:
      - ./conf/env/mysql.env
    volumes:
      - /mnt/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  prometheus:
    container_name: prometheus
    image: 192.168.3.201:80/library/prom/prometheus:latest
    volumes:
      - ./conf/prometheus/prometheus-standalone.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - nacos
    restart: on-failure
  grafana:
    container_name: grafana
    image: 192.168.3.201:80/library/grafana/grafana:latest
    ports:
      - 3000:3000
    restart: on-failure

