# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["promethus.in.gen10.mly0110.org.cn:9090"]

  - job_name: "nacos"
    metrics_path: "/nacos/actuator/prometheus"
    static_configs:
      - targets: ["nacos.in.gen10.mly0110.org.cn:8848"]

  - job_name: "mysql"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["nacos-mysql.in.gen10.mly0110.org.cn:9104"]

  
  - job_name: "elasticsearch"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["kibana-es.in.gen10.mly0110.org.cn:9114"]

  - job_name: "node"
    scrape_interval: 8s
    static_configs:
      - targets:
          [
            "node-206.in.gen10.mly0110.org.cn:9100",
            "node-205.in.gen10.mly0110.org.cn:9100",
            "node-204.in.gen10.mly0110.org.cn:9100",
            "node-203.in.gen10.mly0110.org.cn:9100",
            "node-202.in.gen10.mly0110.org.cn:9100",
            "node-201.in.gen10.mly0110.org.cn:9100",
            "node-200.in.gen10.mly0110.org.cn:9100",
          ]
          
  - job_name: "kong"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["kong.in.gen10.mly0110.org.cn:8001"]