---
# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: null
# my global config
global:
  evaluation_interval: 15s
  scrape_interval: 15s
# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files: null
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus.operation.in.mly0110.org.cn:9999"]
  - job_name: nacos
    metrics_path: /nacos/actuator/prometheus
    static_configs:
      - targets: ["nacos.operation.in.mly0110.org.cn:8848"]
  - job_name: nacos-mysql
    metrics_path: /metrics
    static_configs:
      - targets: ["nacos-mysql.operation.in.mly0110.org.cn:9104"]
  - job_name: mysql
    metrics_path: /metrics
    static_configs:
      - targets: ["mysql.database.in.mly0110.org.cn:9104"]
  - job_name: node
    scrape_interval: 8s
    static_configs:
      - targets:
          [
            "node-200.exporter.in.mly0110.org.cn:9100",
            "node-210.exporter.in.mly0110.org.cn:9100",
            "node-211.exporter.in.mly0110.org.cn:9100",
            "node-212.exporter.in.mly0110.org.cn:9100",
            "node-213.exporter.in.mly0110.org.cn:9100",
            "node-231.exporter.in.mly0110.org.cn:9100",
            "node-232.exporter.in.mly0110.org.cn:9100",
            "node-233.exporter.in.mly0110.org.cn:9100",
            "node-234.exporter.in.mly0110.org.cn:9100",
            "node-235.exporter.in.mly0110.org.cn:9100",
            "node-240.exporter.in.mly0110.org.cn:9100",
            "node-241.exporter.in.mly0110.org.cn:9100",
          ]
  - job_name: harbor-exporter
    metrics_path: /metrics
    scrape_interval: 20s
    static_configs:
      - targets: ["harbor.dependency.in.mly0110.org.cn:9999"]
  - job_name: harbor-core
    metrics_path: /metrics
    params:
      comp: ["core"]
    scrape_interval: 20s
    static_configs:
      - targets: ["harbor.dependency.in.mly0110.org.cn:9999"]
  - job_name: harbor-registry
    metrics_path: /metrics
    params:
      comp: ["registry"]
    scrape_interval: 20s
    static_configs:
      - targets: ["harbor.dependency.in.mly0110.org.cn:9999"]
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: harbor-jobservice
    metrics_path: /metrics
    params:
      comp: ["jobservice"]
    scrape_interval: 20s
    static_configs:
      - targets: ["harbor.dependency.in.mly0110.org.cn:9999"]
    # scheme defaults to 'http'.# - "first_rules.yml"
  # - "second_rules.yml"          # - alertmanager:9093  # scrape_timeout is set to the global default (10s).
  - job_name: kong
    metrics_path: /metrics
    params:
      comp: ["registry"]
    scrape_interval: 20s
    static_configs:
      - targets: ["kong.service.in.mly0110.org.cn:8001"]

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongodb.database.in.mly0110.org.cn:9216"]
