# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["prometheus.operation.in.mly0110.org.cn:9999"]

  - job_name: "nacos"
    metrics_path: "/nacos/actuator/prometheus"
    static_configs:
      - targets: ["nacos.operation.in.mly0110.org.cn:8848"]

  - job_name: "mysql"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["nacos-mysql.operation.in.mly0110.org.cn:9104"]

  - job_name: "node"
    scrape_interval: 8s
    static_configs:
      - targets:
          [
            "node-231.operation.in.mly0110.org.cn:9100"
            "node-232.operation.in.mly0110.org.cn:9100"
          ]
          
  - job_name: 'harbor-exporter'   #从Harbor exporter组件中获取度量
      scrape_interval: 20s
      static_configs:
      - targets: ['harbor.dependency.in.mly0110.org.cn:9999/metrics']
  - job_name: 'harbor-core'
    scrape_interval: 20s
    params:
      comp: ['core']    #从Harbor core组件中获取度量
    static_configs:
      - targets: ['harbor.dependency.in.mly0110.org.cn:9999/metrics']
  - job_name: 'harbor-registry'
    scrape_interval: 20s
    params:
      comp: ['registry']   #从Harbor registry组件中获取度量
    static_configs:
      - targets: ['harbor.dependency.in.mly0110.org.cn:9999/metrics']
  - job_name: 'harbor-jobservice'
    scrape_interval: 20s
    params:
      comp: ['jobservice']  # 从Harbor jobservice组件中获取度量
    static_configs:
      - targets: ['harbor.dependency.in.mly0110.org.cn:9999/metrics']